# 101 NumPy Exercises for Data Analysis (Python)

 _Source:  https://www.machinelearningplus.com/python/101-numpy-exercises-python/_

** 1.- Import numpy as np and see the version**

In [1]:
import numpy as np
np.__version__

'1.14.0'

** 2.- How to create a 1D array? **
   - Create a 1D array of numbers from 0 to 9

In [5]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

** 3.- How to create a boolean array? **
  - Create a 3×3 numpy array of all True’s

In [16]:
a = np.ones((3,3), dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

** 4.- How to extract items that satisfy a given condition from 1D array? **
   - Extract all odd numbers from arr

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 != 0]



array([1, 3, 5, 7, 9])

** 5.- How to replace items that satisfy a condition with another value in numpy array? **
  - Replace all odd numbers in arr with -1

In [10]:
arr[arr%2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

** 6.- How to replace items that satisfy a condition without affecting the original array? **
  - Replace all odd numbers in arr with -1 without changing arr

In [18]:
arrModified = np.copy(arr)
arrModified[arrModified%2 != 0] = -1
# alternatively use
# arrModified = np.where(arr % 2 == 1,  -1, arr)
print(arr)
print(arrModified)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


** 7.- How to reshape an array? **
  - Convert a 1D array to a 2D array with 2 rows

In [25]:
arr = np.arange(10)
arr.reshape(2,5)
# alternative use
# arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

** 8.- How to stack two arrays vertically? **
  - Stack arrays a and b vertically

In [38]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis = 0)
# Method 2:
#np.vstack([a, b])
# Method 3:
#np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

** 9.- How to stack two arrays horizontally? **
   - Stack the arrays a and b horizontally.

In [39]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis = 1)
# Method 2:
#np.hstack([a, b])

# Method 3:
#np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

** 10.- How to generate custom sequences in numpy without hardcoding? **
  - Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [56]:
a = np.array([1,2,3])
b = np.repeat(a, [3,3,3])
np.hstack([b, np.tile(a, 2)])

# alternative use
#np.r_[np.repeat(a, 3), np.tile(a, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3])

** 11.- How to get the common items between two python numpy arrays? **
   - Get the common items between a and b

In [66]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)


array([2, 4])

** 12.- How to remove from one array those items that exist in another? **
  - From array a remove all items present in array b

In [78]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a,b)
a[np.isin(a,b, invert=True)]

# Alternative use
# np.setdiff1d(a,b)

[1 2 3 4 5] [5 6 7 8 9]


array([1, 2, 3, 4])

** 13.- How to get the positions where elements of two arrays match? **
   - Get the positions where elements of a and b match

In [81]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

** 14.- How to extract all numbers between a given range from a numpy array? **
   - Get all items between 5 and 10 from a.

In [98]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a
a[(a>=5) & (a<=10)]

# Alternative use
# np.where((a>=5) & (a<=10))

array([ 6,  9, 10])

** 15.- How to make a python function that handles scalars to work on numpy arrays? **
  - Convert the function maxx that works on two scalars, to work on two arrays.

In [110]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pairMax = np.vectorize(maxx)

pairMax(a,b)
    

array([6, 7, 9, 8, 9, 7, 5])

** 16.- How to swap two columns in a 2d numpy array? **
  - Swap columns 1 and 2 in the array arr.

In [146]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

** 17.- How to swap two rows in a 2d numpy array? **
  - Swap rows 1 and 2 in the array arr:

In [147]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[1,0,2],: ]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

** 19.- How to reverse the columns of a 2D array? **
  - Reverse the columns of a 2D array arr.

In [154]:
arr = np.arange(9).reshape(3,-1)
print(arr)

arr[:,::-1]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

** 20.- How to create a 2D array containing random floats between 5 and 10? **
   - Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [169]:
x = np.random.uniform(5,10, size=(5,3))
x

array([[8.64128082, 7.90304249, 5.69307691],
       [7.1679364 , 9.37886172, 7.51012144],
       [9.23000027, 5.86419845, 8.79863706],
       [5.62736394, 9.94383594, 6.01858064],
       [8.44725249, 8.75168736, 7.32301138]])